# Generated by Django 5.0.3 on 2024-05-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="nba team's name")),
                ('description', models.TextField(verbose_name="nba team's description")),
                ('conference', models.CharField(max_length=255, verbose_name="nba team's conference")),
                ('division', models.CharField(max_length=255, verbose_name="nba team's division")),
                ('stadium', models.CharField(max_length=255, verbose_name="nba team's home stadium")),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="player's name")),
                ('games_played', models.IntegerField(verbose_name="player's game amount")),
                ('minutes_per_game', models.FloatField(verbose_name="player's minutes per game")),
                ('points_per_game', models.FloatField(verbose_name="player's points per game")),
                ('rebounds_per_game', models.FloatField(verbose_name="player's rebounds per game")),
                ('assists_per_game', models.FloatField(verbose_name="player's assists per game")),
                ('field_goal_pct', models.FloatField(verbose_name="player's fg%")),
                ('three_point_pct', models.FloatField(verbose_name="player's 3p%")),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DialogflowApp.team', verbose_name="player's team")),
            ],
        ),
    ]
