# Generated by Django 5.0.3 on 2024-05-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DialogflowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name="Game's date time")),
                ('home_team_score', models.IntegerField(verbose_name='home team score')),
                ('guest_team_score', models.IntegerField(verbose_name='guest team score')),
                ('quarter1_home_score', models.IntegerField(verbose_name='quarter1 home score')),
                ('quarter1_guest_score', models.IntegerField(verbose_name='querter1 guest score')),
                ('quarter2_home_score', models.IntegerField(verbose_name='quarter2 home score')),
                ('quarter2_guest_score', models.IntegerField(verbose_name='quarter2 guest score')),
                ('quarter3_home_score', models.IntegerField(verbose_name='quarter3 home score')),
                ('quarter3_guest_score', models.IntegerField(verbose_name='quarter3 guest score')),
                ('quarter4_home_score', models.IntegerField(verbose_name='quarter4 home score')),
                ('quarter4_guest_score', models.IntegerField(verbose_name='quarter4 guest score')),
                ('home_team_attempts', models.IntegerField(verbose_name='home team attempts')),
                ('home_team_field_goal_pct', models.FloatField(verbose_name='home team fg%')),
                ('home_team_3p_pct', models.FloatField(verbose_name='home team 3p%')),
                ('home_team_rebounds', models.IntegerField(verbose_name='home team rebounds')),
                ('guest_team_attempts', models.IntegerField(verbose_name='guest team attempts')),
                ('guest_team_field_goal_pct', models.FloatField(verbose_name='guest team fg%')),
                ('guest_team_3p_pct', models.FloatField(verbose_name='guest team 3p%')),
                ('guest_team_rebounds', models.IntegerField(verbose_name='guest team rebounds')),
                ('guest_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team_id', to='DialogflowApp.team', verbose_name='guest team')),
                ('home_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_id', to='DialogflowApp.team', verbose_name='home team')),
                ('mvp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DialogflowApp.player', verbose_name='MVP of the game')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
