# Generated by Django 5.0.3 on 2024-05-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DialogflowApp', '0005_remove_game_mvp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatisticpergame',
            name='api_id',
        ),
    ]
