# Generated by Django 5.0.3 on 2024-05-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DialogflowApp', '0006_remove_playerstatisticpergame_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstatisticpergame',
            old_name='pFoulds',
            new_name='pFouls',
        ),
    ]
